### ISSUE TITLE
What is the main reason to push a brand new bundle to backend after installing?

### ISSUE THREAD

**Issue by myshov** [mutantcornholio/veendor#13]
For me it seems redundant to push new bundle to backend every time after `veendor install`. The point is someone can modify package.json file and after that run `veendor install`. And this "experimental" modules will be saved in backend. It seems not so clean. I think that steps for installing and pushing to backend must be split into different commands.

**Comment by mutantcornholio** [comment]
What's the problem with running `npm install` while developing?

If push will be disabled by default, no one will run it and, therefore, no one will get fresh bundles automatically. 

If disk space is the problem, `push` option in `.veendor.js` might be evaluated from external source, like environment variable, and set it in build environment, or other environment that will be used to populate the cache.

**Comment by myshov** [comment]
Anyway I think that every push to backend must be done only by CI system or with a conscious users decision.

**Comment by mutantcornholio** [comment]
btw, `push: true` is not a default setting.
