### ISSUE TITLE
[feature request] Add indication for downloading process

### ISSUE THREAD

**Issue by myshov** [mutantcornholio/veendor#19]
Hi!
It would be nice to see a current percent of the downloaded artifact. It can be just number or ascii progress bar.

**Comment by mutantcornholio** [comment]
Yep, i've been thinking about that too. It requires some kind of feedback API for each backend to signal it's progress (maybe logging and some other stuff too).
Looks pretty straightforward, I'll try to implement in a version or two.

**Comment by mutantcornholio** [comment]
Done!

You can try new `3.0.0-alpha.1` version
**UPD:** `3.0.0-alpha.2`
